# Generated by Django 5.2 on 2025-04-03 15:36

import uuid

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_github_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreApprovedAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "github_login",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("github_id", models.IntegerField(blank=True, null=True)),
                (
                    "github_node_id",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=512, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField()),
                (
                    "document",
                    markdownx.models.MarkdownxField(
                        help_text=(
                            "The document that contributors will sign "
                            "<b>cannot</b> be edited or deleted after it has been created. "
                            "You will have to draft, save, and assign a new document"
                        )
                    ),
                ),
                ("default", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("default", True)),
                        fields=("default",),
                        name="only_one_default_agreement",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PendingSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_repository_id", models.IntegerField()),
                ("ref", models.CharField(max_length=512)),
                ("email_address", models.EmailField(max_length=512)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cla.agreement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepositoryMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cla.agreement"
                    ),
                ),
                (
                    "github_repository",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_github_app.repository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_login", models.CharField(max_length=512)),
                ("github_id", models.IntegerField(blank=True, null=True)),
                (
                    "github_node_id",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("email_address", models.EmailField(max_length=512)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cla.agreement"
                    ),
                ),
            ],
        ),
    ]
