# Generated by Django 5.2 on 2025-04-03 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreApprovedAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "github_login",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("github_id", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=512, null=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="signature",
            old_name="github_username",
            new_name="github_login",
        ),
        migrations.AddField(
            model_name="signature",
            name="github_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
