# Generated by Django 5.2 on 2025-04-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="compatible",
            field=models.ManyToManyField(blank=True, to="cla.agreement"),
        ),
    ]
