# Generated by Django 5.2 on 2025-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0002_agreement_compatible"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="signing_email_address",
            field=models.EmailField(blank=True, max_length=512, null=True),
        ),
    ]
