# Generated by Django 5.2 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0002_preapprovedaccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="preapprovedaccount",
            name="github_node_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="signature",
            name="github_node_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="preapprovedaccount",
            name="github_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="signature",
            name="github_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
