# Generated by Django 5.2 on 2025-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0003_preapprovedaccount_github_node_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
