# Generated by Django 5.2 on 2025-04-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0003_signature_signing_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsignature",
            name="pull_number",
            field=models.IntegerField(null=True),
        ),
    ]
