# Generated by Django 5.2 on 2025-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0005_repositorymapping_delete_repository"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agreement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True)),
                fields=("default",),
                name="only_one_default_agreement",
            ),
        ),
    ]
