# Generated by Django 5.2 on 2025-04-03 09:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0006_agreement_only_one_default_agreement"),
        ("django_github_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref", models.CharField(max_length=512)),
                ("email_address", models.EmailField(max_length=512)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cla.agreement"
                    ),
                ),
                (
                    "github_repository",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_github_app.repository",
                    ),
                ),
            ],
        ),
    ]
