# Generated by Django 5.2 on 2025-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0007_pendingsignature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingsignature",
            name="github_repository",
        ),
        migrations.AddField(
            model_name="pendingsignature",
            name="github_repository_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
