# Generated by Django 5.2 on 2025-04-03 10:34

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0008_remove_pendingsignature_github_repository_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="document",
            field=markdownx.models.MarkdownxField(default=" "),
            preserve_default=False,
        ),
    ]
