services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: clabot
      POSTGRES_PASSWORD: clabot
      POSTGRES_DB: clabot
      POSTGRES_HOST_AUTH_METHOD: trust  # never do this in production!
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "clabot", "-d", "clabot"]
      interval: 1s

  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: clabot:docker-compose
    environment: &base_environment
      DEBUG: "True"
      DJANGO_SECRET_KEY: "deadbeef"
      DATABASE_URL: postgresql://clabot:clabot@postgres:5432/clabot
    volumes: &base_volumes
      - .:/code

  web:
    image: clabot:docker-compose
    command: memray run --native --follow-fork -f -m gunicorn -c gunicorn.conf.dev.py clabot.asgi:application --log-file -
    environment: *base_environment
    ports:
      - "8000:8000"
    volumes: *base_volumes
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    image: clabot:docker-compose
    command: python manage.py runworker
    environment: *base_environment
    volumes: *base_volumes
    depends_on:
      postgres:
        condition: service_healthy
