# Generated by Django 5.2 on 2025-04-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agreement",
            name="agreement_txt",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
    ]
