# Generated by Django 5.2 on 2025-04-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="github_repository",
            field=models.CharField(default=" ", max_length=512),
            preserve_default=False,
        ),
    ]
